### ISSUE TITLE
Images on projects overview extremely slow to load

### ISSUE THREAD

**Issue by libeclipse** [TaylanTatli/Halve#36]
Title is self-explanatory. Images on the project overview are very very slow to load. Is there anything that can be done to improve them, or at least something to indicate that they're loading?

**Comment by tanto259** [comment]
I have the same issue, even with Netlify images would load at around 1 second or so.

But when I open your project overview I noticed that the images loaded at around 3 seconds, that's way longer than the time my images loaded.

Then I started to dig around, I live in Indonesia, when I dig my website, I got served from an Amazon server in Singapore. But when I dig your website, I got served from an Amazon server in Japan. 

This could be the case with the ALIAS processing server location of DNSimple. 

I know this since I had this kind of issue when using another DNS service, so I move my DNS to Cloudflare. 

As a comparison try pinging cryptolosophy.io and www.cryptolosophy.io and compare the ping time.

Hope this helps

**Comment by libeclipse** [comment]
@tanto259 Ah, that actually explains a lot. I remember reading something about Netlify's CDN only working properly for the www subdomain. I'll look into it and report back.

**Comment by tanto259** [comment]
For reference, [DNSimple have 5 servers worldwide](https://support.dnsimple.com/articles/anycast/) (3 in USA, 1 in Netherlands and 1 in Japan). This would explain why I am served from Japan.

**Comment by libeclipse** [comment]
Ping times are similar for me for both sub-domains, hovering around ~30ms. The IPs are different though so the similar times are probably explained by me being in the UK. Will ping a support request at Netlify see if they know what's up.

**Comment by libeclipse** [comment]
I'll close this issue since I've since removed the entire projects section from my version of the site. If someone else (@tanto259) is suffering from the same problem, feel free to re-open this.
